{% set version = "0.5.0" %}

package:
    name: fabio
    version: {{ version }}

source:
    url: https://github.com/silx-kit/fabio/archive/v{{ version }}.tar.gz
    fn: fabio-v{{ version }}.tar.gz
    sha256: ae1f2f979f801524558cac81ec8988d1eadce65b540cdeb46166162ae4788956

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy 1.10.*
        - cython
        # could use opencl, but need the package on conda-forge first
        # - opencl

    run:
        - python
        - numpy >=1.10

test:
    imports:
        - fabio
        - fabio.test
        - fabio.third_party

about:
    home: https://github.com/silx-kit/fabio
    license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
    summary: I/O library for images produced by 2D X-ray detector
    license_family: Other
    license_file: copyright

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - dmpelt
        - CJ-Wright
