travis:
  secure:
    BINSTAR_TOKEN: ii6vSgOfZo16Lc0P2fENDFiAuYcGWC1HnLnX55xRuWCDmuons4QozTaGpvKKqb7ul9wcmCZVJQ/oU4T7dedlllnUSbDDq+BStUGJodaHyebVaxLxTmK2egY4ykhLyVQ8JcSYAXbngVmyz3WU+seDLF58R32QMU3fQCbEBjiAISpF1ahXH66bctFU3Hba0UE1JmNk9HqOdqdUU5MUsTV0nm/jvxKI+dxgWfkzwG0/nWH20zl13JFRz7Gjwz/iCkuvGSDl7AVUdlxF+bXzdX9t3UjY/5wYkcl2+6ZDmScxVk6KAJOyXubxG2NlVjDnrKzBdi1ZszZehsRUQ6kTxHEt6Rz2mB44qUUUW7OO8iuqz3Q2/RLyhrIHEhXEfja4305HCdKkU/cn7Du3SuNNWNcsTC4rin+beacFBLvvI8wtMXVUaSi8ZAqI05lB4XOF1DGo9edKcSIA6BmkcGQXpiUOzh5VQp1L2I8UyKl99A1KY/ZNNfdNamyS261JJUFs7MuyLy5aL0hvYFWbugbA2BjHiOuMyF9yrn1pan5iaX62KphVNJ1F9EE/AIHcJv+Ko8EAjb/gbPmn+8ZP9VG5NqoGdMO6Ak9kzitfW69tcvcvMEfPkrYTVHUEH8XWwzrcN3jd+zOE7L9Mk3PMiRrJS+sY0jW9x7IJBVZTwckU5Y+cr/s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
