travis:
  secure:
    BINSTAR_TOKEN: h3gO3lLO0qVPdP51G39W2hL4Xoh9Xmy7tpJrrU9qiwcpXBDOdb1X37R61HXrADJVywxYaGfLnIkX/A9UPWhhNDnBcTzGd98ml6oGsGpFXOyzLi43hjEpt/BixMQJfydyfXDDWZu+KjGF0wnyC6lSPBsn/1rIUJwsE+4abdR+mn1KkOeUzsi+4WHDes3DOrXS3Cql2sAXExAZw29A+q3e0aulTTylpkSptUH7wiDnIc0Y1j4l8W+bZ5Cw1ga7VlTIOOdIKgOQC//ww9Nx4T1WIhfTHmRA9iLp1xEDw3H/P5w2RkNVizzA0sSDTOCjTjupBh7JG9EZugwmELwZxp3c+As4O5wowOCfvw3u/rJE20Igot2xcFu2FwYnqXTYWG99hvHGAHjXbokpC7K8gqrA6Q6WZOFJQOltpC/B9mFRYXsLr1CLE6M61V5GqIiPRZwcxX2cfTY6nVcobPqOZuI38tTLbLtpiAnlqtD3zFGWSw1J9G8yKyKPdKFeTNw3NK9jLPYM6U4kxKB8+HSUHkdGdpEBb+dXOxG/Ss0GHjX3DSCPWFj9qgOcoBdN09h3YhxzEJ7YyidqVMmY9MMljdrmX5Jqx0/dCnef7ZYUKg/IssqWOTV0wg6LlXQYX0oVs2TiW5PvAzhH784bsRIB9Y5GjzU9jlvN9r4Xz4vmhyGXvEY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
